packaging_format = 2

id = "zulip"
name = "Zulip"
description.en = "Chat that helps teams stay productive and focused"
description.fr = "Chat qui aide les équipes à rester productives et concentrées"

version = "7.4~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://zulip.com/"
admindoc = "https://zulip.readthedocs.io/"
code = "https://github.com/zulip/zulip"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/zulip/zulip/releases/download/8.0-beta1/zulip-server-8.0-beta1.tar.gz"
        sha256 = "7c01ef5d779dd747c01e2d10bba830bd34a578de831cb12a475cb253e2e8cf21"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    #[resources.apt]
    #packages = "postgresql"

    #[resources.database]
    #type = "postgresql"
